### ISSUE TITLE
Mac adress won't assign

### ISSUE THREAD

**Issue by TnTCreeperLpr** [softgrass/govee-api-ble#4]
![Screenshot_20220806-210247_Pydroid 3.jpg](https://user-images.githubusercontent.com/71041679/183273216-3937cee7-433a-4af7-a452-bf4abde91011.jpg)

```
import asyncio
import weatherbug_spark
from govee_api_ble import GoveeDevice


async def main():
    #South Pool
    data1 = await weatherbug_spark.get_data(39.5842042, -104.9077378)    
    roundeddata1 = round(data1.closestPulseDistance,2)
    print("South Pool Strike Distance= ",roundeddata1);
    my_device = GoveeDevice(7C:A6:B0:1F:8E:63)
    my_device.setPower(True) # Turns device on
    
    #Middle of Centennnial
    data3 = await weatherbug_spark.get_data(39.579231, -104.876694)
    roundeddata3 = round(data3.closestPulseDistance,2) 
    print("Middle Of Centennial Strike Distance= ",roundeddata3)
    
    #Centennial Airport
    data2 = await weatherbug_spark.get_data(39.5795, -104.8463)
    roundeddata2 = round(data2.closestPulseDistance,2) 
    print("Centennial Airport Strike Distance= ",roundeddata2)
    
    print(" ")
    print("Pool Status: ")
    if roundeddata1 >= 30:
        print("Not even Close")
    elif roundeddata1 >= 10:
        print("Its getting there")
    elif roundeddata1 > 6:
        print("Nearly there")
    elif roundeddata1 > 5:
        print("Close the pool")
    elif roundeddata1 < 3:
        print("Kick everyone out")
        
if __name__ == "__main__":
    asyncio.run(main())
    
```

**Comment by softgrass** [comment]
Hi! I completely forgot to specify in the docs, but when you assign your device you need quotes around you MAC address

Ex:

`my_device = GoveeDevice(‘7C:A6:B0:1F:8E:63’)`

If you have any other questions feel free to ask :-))

**Comment by TnTCreeperLpr** [comment]
Now I get this![Screenshot_20220806-212000_Pydroid 3.jpg](https://user-images.githubusercontent.com/71041679/183273592-285ef259-f00e-4fc0-bb50-a82d7152f2ac.jpg)

**Comment by softgrass** [comment]
You need gatttool installed for this to work. You’re running this on Android (I believe), so you need to find a way to install gatttool. This API works best on a Linux system like a Raspberry Pi

**Comment by TnTCreeperLpr** [comment]
Yeah I was doing this while I work where I couldn't access the pi, but once i do would it work?

**Comment by softgrass** [comment]
It should work fine

**Comment by TnTCreeperLpr** [comment]
When using it on my ras pi it still says the same thing

**Comment by TnTCreeperLpr** [comment]
It still says the same thing![Screenshot_20220807-101345_Putty SSH.jpg](https://user-images.githubusercontent.com/71041679/183300431-744fc51b-812b-4bef-ab9d-2df534e7d4d2.jpg)

**Comment by softgrass** [comment]
Please read your error messages. It says gatttool cannot be found, which means it is not installed, you need to install gatttool (using the BLUEZ package) for this program to work.

**Comment by TnTCreeperLpr** [comment]
When trying to install bluez 5.9 using this how to https://www.instructables.com/Control-Bluetooth-LE-Devices-From-A-Raspberry-Pi/

![Screenshot_20220807-103322_Putty SSH.jpg](https://user-images.githubusercontent.com/71041679/183301369-b4c90642-728a-475f-aff5-c9e647feaa3b.jpg)

Getting error between these two steps
![Screenshot_20220807-103553_Chrome.jpg](https://user-images.githubusercontent.com/71041679/183301484-36f00531-2b8b-46cd-a04c-28b6dd4b5ee8.jpg)

**Comment by TnTCreeperLpr** [comment]
Ok I fixed the error but now I get thus
![Screenshot_20220807-112200_Putty SSH.jpg](https://user-images.githubusercontent.com/71041679/183303186-56ac4c79-08c7-4de6-8b5a-7d5cc51b3fab.jpg)

**Comment by softgrass** [comment]
According to [this guide](https://www.jaredwolff.com/get-started-with-bluetooth-low-energy/#connect-to-your-bluetooth-low-energy-device), it says `If you get a connect: No route to host (113), that means the device is not advertising, you’ve used the wrong address or you haven’t run sudo hcitool lescan before opening gatttool.`

Hope this helps, you may have the wrong MAC address, or are too far from the lights.

**Comment by TnTCreeperLpr** [comment]
Now I'm getting this
![Screenshot_20220807-195042_Putty SSH.jpg](https://user-images.githubusercontent.com/71041679/183322874-056309c9-a345-48b8-a140-3843fb01e1eb.jpg)

**Comment by softgrass** [comment]
From what it looks like, you are using the iHoment H6110 light strip, this API is guaranteed to work **only** with the H6127 light strip. Your light strip has wifi and other features built in to it, so please consider using a different way than BLE to control them (especially because of how inefficient BLE is. It is only used on this because the H6127 lights only use bluetooth).
