### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by TnTCreeperLpr** [softgrass/govee-api-ble#5]
Using a Raspberry PI 4 (Ubuntu server 20.4) and a Govee led strip

When running this code
```
from govee_api_ble import GoveeDevice
my_device = GoveeDevice('7C:A6:B0:1F:8E:63')
my_device.setPower(True) # Turns device on
```

It gives me this error
![Screenshot_20220807-150539_Putty SSH.jpg](https://user-images.githubusercontent.com/71041679/183310961-bb931ba5-b092-47d9-b0e2-3a50effd6934.jpg)

**Comment by softgrass** [comment]
Please see the comment on #4 

Your lights are not supported, and this issue was solved in another comment on your last issue post
