### ISSUE TITLE
H6139 model also mostly working

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [softgrass/govee-api-ble#6]
Hi, thanks for building and documenting this!

Just commenting to say the H6139 model is also working, you may want to add this to the README - At least the power on/off, setColor, setBrightness, setScene and setBrightness abilities. The setColorMusic might not be working for this specific model, haven't fully tested it.

**Comment by softgrass** [comment]
Meant to fix this *wayyy* earlier, but it has been added! Thank you so much for testing :-)
